# Generated by Django 4.0.6 on 2022-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='person',
            name='car1',
            field=models.CharField(default=1, max_length=100, verbose_name='CAR 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='car2',
            field=models.CharField(default=2, max_length=100, verbose_name='CAR 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='car3',
            field=models.CharField(default=1, max_length=100, verbose_name='CAR 3'),
            preserve_default=False,
        ),
    ]
