# Generated by Django 4.0.6 on 2022-07-15 16:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('OCP', '0002_details_delete_product_person_car1_person_car2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='full name')),
                ('Columns', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
