# Generated by Django 4.0.6 on 2022-07-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCP', '0003_info_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
            ],
        ),
    ]
