# Generated by Django 4.0.6 on 2022-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCP', '0004_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='layer name')),
                ('BPL', models.FloatField(default=0, verbose_name='BPL value')),
                ('MgO', models.FloatField(default=0, verbose_name='MgO value')),
                ('MO', models.FloatField(default=0, verbose_name='MO value')),
                ('SiO2', models.FloatField(default=0, verbose_name='SiO2 value')),
                ('CO2', models.FloatField(default=0, verbose_name='CO2 value')),
            ],
        ),
        migrations.AlterField(
            model_name='details',
            name='City',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='details',
            name='First_Name',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='details',
            name='Last_Name',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
