# Generated by Django 4.0.6 on 2022-08-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OCP', '0005_detail_alter_details_city_alter_details_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='layers',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='OCP.detail')),
                ('SM_BO', models.FloatField(default=0, verbose_name='SM_BO')),
                ('SM_MZ', models.FloatField(default=0, verbose_name='SM_MZ')),
                ('MAT_NIF', models.FloatField(default=0, verbose_name='MAT_NIF')),
                ('SFA', models.FloatField(default=0, verbose_name='SFA')),
                ('DSP', models.FloatField(default=0, verbose_name='C2_Sup')),
                ('C2_Sup', models.FloatField(default=0, verbose_name='C2_Sup')),
                ('C4_inf', models.FloatField(default=0, verbose_name='C4_inf')),
                ('C5_supA', models.FloatField(default=0, verbose_name='C5_supA')),
                ('C5_inf', models.FloatField(default=0, verbose_name='C5_inf')),
                ('C6_sm', models.FloatField(default=0, verbose_name='C6_sm')),
                ('C6_inf', models.FloatField(default=0, verbose_name='C6_inf')),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='detail',
            name='Mix',
            field=models.FloatField(default=0, verbose_name='mix value'),
        ),
    ]
