# Generated by Django 4.0.6 on 2022-08-16 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OCP', '0006_layers_delete_details_delete_info_delete_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'ordering': ('-id',)},
        ),
    ]
